### ISSUE TITLE
モデル周りを把握したいので、ドキュメントを作る

### ISSUE THREAD

**Issue by pollseed** [springhackathon/harmox-user#26]
### er図
- [x] https://github.com/voormedia/rails-erd で pdf生成
### モデルを見てschemaを把握したい
- [x] https://github.com/ctran/annotate_models modelsにコメント付与
### SQL文を詳しく開発中に見る
- [x] https://github.com/dejan/rails_panel  
- [x] https://chrome.google.com/webstore/detail/railspanel/gjpfobpafnhjhbajcjgccbbdofdckggg ここでクローム拡張をインストールする

**Comment by Gaddict** [comment]
commit ok
